server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://im-here.cn:3306/shorturl
    username: root
    password: 19980411
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /
      suffix: .html